export const RABBITMQ_URL = process.env.RABBITMQ_URL;
export const RABBITMQ_INFOBIP_EXCHANGE = process.env.RABBITMQ_INFOBIP_EXCHANGE;
export const RABBITMQ_CEQUENS_EXCHANGE = process.env.RABBITMQ_CEQUENS_EXCHANGE;
export const RABBITMQ_ARPUPLUS_EXCHANGE =
  process.env.RABBITMQ_ARPUPLUS_EXCHANGE;
  export const RABBITMQ_SMSGLOBAL_EXCHANGE =
  process.env.RABBITMQ_SMSGLOBAL_EXCHANGE;
export const RABBITMQ_SMS_EXCHANGE = process.env.RABBITMQ_SMS_EXCHANGE;
export const RABBITMQ_SMS_EXCHANGE_ROUTING =
  process.env.RABBITMQ_SMS_EXCHANGE_ROUTING;
export const RABBITMQ_SMS_FAILURE_EXCHANGE =
  process.env.RABBITMQ_SMS_FAILURE_EXCHANGE;
export const RABBITMQ_SMS_EXCHANGE_RETRY =
  process.env.RABBITMQ_SMS_EXCHANGE_RETRY;
export const RABBITMQ_SMS_FAILURE_EXCHANGE_ROUTING =
  process.env.RABBITMQ_SMS_FAILURE_EXCHANGE_ROUTING;
export const RABBITMQ_QUEUE_INFOBIP_P1 = process.env.RABBITMQ_QUEUE_INFOBIP_P1;
export const RABBITMQ_QUEUE_INFOBIP_P2 = process.env.RABBITMQ_QUEUE_INFOBIP_P2;
export const RABBITMQ_QUEUE_CEQUENS_P1 = process.env.RABBITMQ_QUEUE_CEQUENS_P1;
export const RABBITMQ_QUEUE_CEQUENS_P2 = process.env.RABBITMQ_QUEUE_CEQUENS_P2;
export const RABBITMQ_QUEUE_WEB_P1 = process.env.RABBITMQ_QUEUE_WEB_P1;

export const RABBITMQ_QUEUE_ARPUPLUS_P1 =
  process.env.RABBITMQ_QUEUE_ARPUPLUS_P1;
export const RABBITMQ_QUEUE_ARPUPLUS_P2 =
  process.env.RABBITMQ_QUEUE_ARPUPLUS_P2;

  export const RABBITMQ_QUEUE_SMSGLOBAL_P1 =
  process.env.RABBITMQ_QUEUE_SMSGLOBAL_P1;
export const RABBITMQ_QUEUE_SMSGLOBAL_P2 =
  process.env.RABBITMQ_QUEUE_SMSGLOBAL_P2;

export const PROVIDER_EXCHANGES = {
  cequens: RABBITMQ_CEQUENS_EXCHANGE,
  infobip: RABBITMQ_INFOBIP_EXCHANGE,
  arpuplus: RABBITMQ_ARPUPLUS_EXCHANGE,
  smsglobal: RABBITMQ_SMSGLOBAL_EXCHANGE,
};
