export const Environment = {
  HOST: process.env.HOST ?? 'http://localhost',
  PORT: process.env.PORT ?? 8080,

  SMS_CEQUENS_CASSBANA_USER_NAME: process.env.SMS_CEQUENS_CASSBANA_USER_NAME,
  SMS_CEQUENS_API_KEY: process.env.SMS_CEQUENS_API_KEY,
  SMS_CEQUENS_ACCESS_TOKEN: process.env.SMS_CEQUENS_ACCESS_TOKEN,

  SMS_CEQUENS_OTP_USER_NAME: process.env.SMS_CEQUENS_OTP_USER_NAME,
  SMS_CEQUENS_OTP_API_KEY: process.env.SMS_CEQUENS_OTP_API_KEY,
  SMS_CEQUENS_OTP_ACCESS_TOKEN: process.env.SMS_CEQUENS_OTP_ACCESS_TOKEN,
  ALLOW_WEB_PORTAL: process.env.ALLOW_WEB_PORTAL,
  ALLOW_SMS_WEB_CHANNEL: process.env.ALLOW_SMS_WEB_CHANNEL,
};
